name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permite que este trabalho clone o repositório e crie uma implantação de página
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Prepare Artifact
        run: |
          mkdir dist
          # Copia todos os arquivos e diretórios de nível superior
          cp index.html index.tsx metadata.json types.ts dist/
          cp -r components services utils dist/
          # Cria o arquivo de chave usando o secret do repositório
          echo "window.GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';" > dist/key.js
          # Injeta a tag de script no arquivo HTML
          sed -i 's|</body>|<script src="key.js"></script></body>|' dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
